#!/bin/sh

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Please read the instructions at
https://marketplace.digitalocean.com/apps/octobot

If you have questions, check out the guides at https://www.octobot.cloud/en/guides/octobot

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
